# Generated by Django 4.1.4 on 2023-02-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=100)),
                ('news_image', models.ImageField(upload_to='NewsImages')),
                ('news_description', models.TextField(default='null')),
            ],
        ),
    ]
